# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nano
tagline:          'A C++ template metaprogramming library'
description:      'A C++ template metaprogramming library designed to provide compile time implementations of common STL and functional programming functions, as well as allowing user-defined metafunctions to be easily implemented using the functions provided by nano'
url:              https://robclu.github.io/nano
baseurl:          /nano

author:
  name:           'Rob Clucas'
  url:              https://robclu.github.io/nano

paginate:         5

# Custom vars
version:          1.0

github:
  repo:          https://github.com/robclu/nano 
